apiVersion: v1
kind: Pod
metadata:
  name: filestore-test-pod-02
  labels:
    app: wordpress-with-nfs
spec:
  containers:
    - image: wordpress:4.8-apache
      name: wordpress-with-nfs
      env:
        - name: WORDPRESS_DB_HOST
          value: mysql.topse.private:3306
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: password
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /data
          name: mypvc
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: fileserver-claim
        readOnly: false

