apiVersion: apps/v1

kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - image: wordpress:4.8-apache
          name: wordpress
          env:
          - name: WORDPRESS_DB_HOST
            value: mysql.topse.private:3306
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql
                key: password
          ports:
            - containerPort: 80
              name: wordpress
          readinessProbe:
                  httpGet:
                          path: /readme.html
                          port: 80
                  initialDelaySeconds: 5
                  periodSeconds: 10
          volumeMounts:
            - mountPath: /data
              name: mypvc
      volumes:
        - name: mypvc
          persistentVolumeClaim:
            claimName: fileserver-claim
            readOnly: false
